#!/usr/bin/env bash
echo "== create bucket "$1""

if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

aws s3api create-bucket \
--bucket $1 \
--create-bucket-configuration="LocationConstraint=ap-southeast-1" \
--query Location \
--output text